### ISSUE TITLE
Amazon Fire HD 8 loged like a Dash Button

### ISSUE THREAD

**Issue by techsolo12** [mwittig/pimatic-amazing-dash-button#12]
Hello,

today I saw in pimatic-daemon.log the IP and MAC Address from my Amazon Fire HD 8. This is the last enrty in my log, after this event the webinterface didn't reachable from my network. Rules didn't performed.

Pimatic-daemon.log:
`21:02:10.957 [pimatic] info: rule dummyswitch-off-variable-0: set $beregnung_aktiv to 0
21:02:10.970 [pimatic] info: rule variable-0-beregnung-off: Pumpe Beregnung ausgeschaltet
21:02:10.975 [pimatic] info: rule variable-0-beregnung-off: Ventil Unten ausgeschaltet
21:02:12.957 [pimatic] info: rule variable-0-beregnung-off: Ventil Oben ausgeschaltet
21:03:09.893 [pimatic] info: rule beregnung-2-dev-2: Ventil Unten ausgeschaltet
21:04:09.700 [pimatic-amazing-dash-button] debug: [Plugin] ARP { mac: 'fc:65:de:fa:0b:09', ip: '192.168.192.123' }
21:04:10.678 [pimatic-amazing-dash-button] debug: [Plugin] ARP { mac: 'fc:65:de:fa:0b:09', ip: '192.168.192.123' }
06:36:07.298 2018-04-03 Tuesday`

MAC Address and IP are from my Amazon Fire HD 8.
When i blocked the MAC Address in router the message didn't appeared anymore.
But i cannot use the Fire HD in network. Make sense. :D

With my Raspberry Pi 2 i didn't have problems like that, after a change to Raspberry Pi 3+ and Raspbian Stretch Lite i had many issues.

**Comment by mwittig** [comment]
Can you please check the log for error messages? From the excerpt you have included I don't see why the web interface should no longer be reachable. The issue might be also be caused by another plugin. Can you please also include a list of plugin you're using in this setup? Thanks

Regarding the detection of "Amazon Fire HD 8" as a candidate dash button, there is not much I can do right now. The plugin already contains a filter to filter out ChromeCast  devices by probing them on port 8008. I guess this doesn't work with a tablet. What I can offer is to add an configuration option to maintain a list of mac addresses which should be ignored.

**Comment by mwittig** [comment]
No response. Closing this now. Please re-open if you wish to follow-up.

**Comment by techsolo12** [comment]
Hello

**Comment by techsolo12** [comment]
Sry for the late response. After you closed this issue i got a email.
The problem was not the dashbutton plugin. My SDcard was corrupted so...
But can you add the mac filter? This would be very nice.

With best regards
techsolo12
